[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PYB_V1.0"
authors = [{name = "TAXI", email = "TAXI@lumache"}]
dynamic = ["version", "description"]
